### ISSUE TITLE
Corner case: -o /dev/null

### ISSUE THREAD

**Issue by BrunoDutertre** [SRI-CSL/whole-program-llvm#8]
Seen in the wild. Some configure scripts test the compiler
by doing things like 'clang test.c -o /dev/null'.  This breaks
with wllvm since we try to create /dev/.null.bc!

**Comment by ianamason** [comment]
Isn't that the use case for:

```
WLLVM_CONFIGURE_ONLY=1
```

?

From the README.md:
- `WLLVM_CONFIGURE_ONLY` can be set to anything. If it is set, `wllvm`
  and `wllvm++` behave like a normal C or C++ compiler. They do not
  produce bitcode.  Setting `WLLVM_CONFIGURE_ONLY` may prevent
  configuration errors caused by the unexpected production of hidden
  bitcode files.
